language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - "pip install -U pytest pytest-cov coveralls fauxfactory"
script: "py.test -v --cov pytest_fauxfactory"
after_success:
    - coveralls